version: '3.7'
services:
  db:
    image: postgres:11.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    image: my-app:v1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=development
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
